"""TAD FILING AEW AMW lane parser.

Same DATA-sheet-shaped raw layout as TAD-OEW-OMW/TAD-WMW-WEW (see those
modules and the project_tad_vba_tool_analysis memory) - two raw sheets,
"AEW" and "AMW", each its own Service Scope and own OPUS output. Real
differences confirmed against reference/2_OPUS/23_TAD FILING AEW AMW:

- **Multi-snapshot filings**: this folder ships TWO raw "AEW"/"AMW" files
  for the same nominal period at different rates - a rate correction
  issued mid-period. Ground truth files both as separate CMDT NOTE blocks,
  the earlier one's validity truncated to end the day before the later
  one's own validity starts. Handled generically by
  parsers/common/tad_snapshots.py (also wired into TAD-OEW-OMW/WMW-WEW).
- **AEW's own CMDT NOTE sheet is literally named "SRCHG"**, not "CMDT
  NOTE" like AMW's (and every other TAD lane) - see
  SCOPED_SHEET_NAME_OVERRIDES. AEW also has NO ROUTE NOTE sheet at all
  (confirmed: zero T/S Port/Service Lane/special-node rows this period) -
  SHEET_NAME_OVERRIDES' "ROUTE NOTE" name still applies to AMW, which does
  use the mechanism (same HAYDARPASA/MARPORT/EGALY special-node table as
  TAD-OEW-OMW's own OMW sheet, reused directly - see
  SPECIAL_NODE_ROUTE_NOTES import - plus a populated Service Lane column,
  combined the same way TAD-WMW-WEW's own _route_note_for() does).
- **D7 (OFT 45)**: the raw MRG never carries this rate slot directly for
  AEW/AMW, but ground truth's own RATES rows do have it populated - equal
  to OFT 40HC (D5) plus a fixed $700 add-on (confirmed: reference/23's own
  "Surcharges" reference sheet documents this add-on; every real GT row
  checked satisfies rate_45 == rate_40hc + 700 exactly). Off by default
  and user-toggleable (config.include_tad_d7/tad_d7_addon) - AEW/AMW only,
  never generated by TAD-OEW-OMW or TAD-WMW-WEW, and only for D/DR rows (a
  generated D/DG duplicate, see config.generate_tad_dg_duplicate, copies
  the same D7 rate across rather than recomputing it).

Origin ARBS (from the raw "Origin ARBS" sheet) and the Japan-origin
scope ("EX.JP AEW"/"EX.JP AMW"/"Origin ARBS - EX JAPAN", surfaced as a
third "JAPAN" output) are a later phase, not yet implemented here.
"""
from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass, field
from datetime import date
from decimal import Decimal, InvalidOperation
from typing import ClassVar

from openpyxl.workbook import Workbook
from openpyxl.worksheet.worksheet import Worksheet

from mrg2opus.parsers.base import BaseMRGParser, RawExtraction
from mrg2opus.parsers.common.commodity import resolve_commodity_code, resolve_commodity_description
from mrg2opus.parsers.common.exclusion import is_excluded
from mrg2opus.parsers.common.tad_snapshots import find_snapshot_sheets, merge_dated_snapshots
from mrg2opus.parsers.registry import LayoutProfile, register
from mrg2opus.parsers.tad_oew_omw import SPECIAL_NODE_ROUTE_NOTES
from mrg2opus.presets.models import MappingProfile
from mrg2opus.schema.charge_codes import CHARGE_CODE_NAMES
from mrg2opus.schema.opus_rows import CmdtNoteRow, OpusRowSet, RatesRow, RouteNoteRow

SHEET_AEW = "AEW"
SHEET_AMW = "AMW"

DATA_MIN_ROW = 2
COL_EFF_DATE, COL_EXP_DATE, COL_SCOPE, COL_CMDT_NAME = 1, 2, 3, 4
COL_POR, COL_POR_DESC, COL_ORIGIN_TERM, COL_ORIGIN_TRANSMODE = 5, 6, 7, 8
COL_POL, COL_POD, COL_DEL, COL_DEL_DESC, COL_DEST_TERM = 9, 10, 11, 12, 13
COL_CARGO_TYPE, COL_TS_PORT, COL_SERVICE_LANE, COL_CUR = 14, 15, 16, 17
COL_OFT20, COL_OFT40, COL_OFTHC, COL_OFT45, COL_INCLUDE_SURCHARGE = 18, 19, 20, 21, 22

# Same CARGO sheet equivalent as every other TAD lane - see tad_oew_omw.py.
CARGO_TYPE_MAP: dict[str, tuple[str, str]] = {
    "Dry General": ("D", "DR"),
    "Reefer": ("R", "RF"),
    "Reefer Dry": ("R", "DR"),
    "Dry Dangerous": ("D", "DG"),
}

DEFAULT_COMMODITY_DESCRIPTION = "FAK"
DEFAULT_COMMODITY_CODE = "G0001"

_HEA_OVERRIDE = "HEAVY SURCHARGE"


def _route_note_for(commodity_name: str, ts_port: str | None, service_lane: str | None) -> str | None:
    """Three independent route-note triggers, all confirmed against
    reference/23's own AMW ground truth (no row seen combines more than
    one, but they'd join with " | " same as TAD-WMW-WEW's identical rule
    if a future file ever does): a recognized special-node commodity-
    group-name tag (reused verbatim from TAD-OEW-OMW's own table), a
    populated T/S Port, and a populated Service Lane."""
    parts = []
    special = SPECIAL_NODE_ROUTE_NOTES.get(commodity_name)
    if special:
        parts.append(special)
    if ts_port:
        parts.append(f"Rates are Subject to Transhipment Port: {ts_port}")
    if service_lane:
        parts.append(f"Rates are applicable for Vessel Service Lane: {service_lane}")
    return " | ".join(parts) if parts else None


def _parse_decimal(text: str | None) -> Decimal | None:
    if not text:
        return None
    try:
        return Decimal(str(text).replace(",", "").strip())
    except InvalidOperation:
        return None


def _parse_date(text: str | None) -> date | None:
    if not text:
        return None
    try:
        return date.fromisoformat(str(text).strip())
    except ValueError:
        return None


def _parse_included_codes(text: str | None) -> list[str]:
    """Same authoritative literal comma-separated list as every other TAD
    lane - see tad_oew_omw.py's comment for why this bypasses
    INDIVIDUAL_CHARGE_CODES. Notably: EX.JP's own rows naturally carry a
    SHORTER list than the main sheet's rows (e.g. missing HEA/LSF) simply
    because each row's own column already says so - no special-casing
    needed for the Japan scope here or in a future phase."""
    if not text:
        return []
    return [c.strip().upper() for c in str(text).split(",") if c.strip()]


@dataclass
class RawRow:
    validity_start: date | None
    validity_end: date | None
    commodity_name: str
    origin_code: str
    origin_description: str
    origin_term: str | None
    origin_transmode: str | None
    pol: str | None
    pod: str | None
    dest_code: str
    dest_description: str
    dest_term: str | None
    cargo_type: str
    ts_port: str | None
    service_lane: str | None
    included_codes: list[str]
    rate_20: Decimal | None
    rate_40: Decimal | None
    rate_40hc: Decimal | None
    rate_45: Decimal | None


@dataclass
class ScopeData:
    scope: str
    rows: list[RawRow] = field(default_factory=list)


def _read_sheet(ws: Worksheet, scope: str) -> ScopeData:
    data = ScopeData(scope=scope)
    for row_idx in range(DATA_MIN_ROW, ws.max_row + 1):
        origin = ws.cell(row=row_idx, column=COL_POR).value
        if origin in (None, ""):
            continue
        origin_cell = ws.cell(row=row_idx, column=COL_POR)
        if is_excluded(origin_cell):
            continue
        data.rows.append(
            RawRow(
                validity_start=_parse_date(ws.cell(row=row_idx, column=COL_EFF_DATE).value),
                validity_end=_parse_date(ws.cell(row=row_idx, column=COL_EXP_DATE).value),
                commodity_name=str(ws.cell(row=row_idx, column=COL_CMDT_NAME).value or "").strip(),
                origin_code=str(origin).strip(),
                origin_description=str(ws.cell(row=row_idx, column=COL_POR_DESC).value or "").strip(),
                origin_term=str(ws.cell(row=row_idx, column=COL_ORIGIN_TERM).value or "").strip() or None,
                origin_transmode=str(ws.cell(row=row_idx, column=COL_ORIGIN_TRANSMODE).value or "").strip() or None,
                pol=str(ws.cell(row=row_idx, column=COL_POL).value or "").strip() or None,
                pod=str(ws.cell(row=row_idx, column=COL_POD).value or "").strip() or None,
                dest_code=str(ws.cell(row=row_idx, column=COL_DEL).value or "").strip(),
                dest_description=str(ws.cell(row=row_idx, column=COL_DEL_DESC).value or "").strip(),
                dest_term=str(ws.cell(row=row_idx, column=COL_DEST_TERM).value or "").strip() or None,
                cargo_type=str(ws.cell(row=row_idx, column=COL_CARGO_TYPE).value or "").strip(),
                ts_port=str(ws.cell(row=row_idx, column=COL_TS_PORT).value or "").strip() or None,
                service_lane=str(ws.cell(row=row_idx, column=COL_SERVICE_LANE).value or "").strip() or None,
                included_codes=_parse_included_codes(ws.cell(row=row_idx, column=COL_INCLUDE_SURCHARGE).value),
                rate_20=_parse_decimal(ws.cell(row=row_idx, column=COL_OFT20).value),
                rate_40=_parse_decimal(ws.cell(row=row_idx, column=COL_OFT40).value),
                rate_40hc=_parse_decimal(ws.cell(row=row_idx, column=COL_OFTHC).value),
                rate_45=_parse_decimal(ws.cell(row=row_idx, column=COL_OFT45).value),
            )
        )
    return data


class TADAewAmwParser(BaseMRGParser):
    lane_id: ClassVar[str] = "TAD-AEW-AMW"
    SHEET_NAME_OVERRIDES: ClassVar[dict[str, str]] = {"route_notes": "ROUTE NOTE"}
    SCOPED_SHEET_NAME_OVERRIDES: ClassVar[dict[str, dict[str, str]]] = {"AEW": {"cmdt_notes": "SRCHG"}}

    @classmethod
    def detect(cls, wb: Workbook) -> float:
        names = set(wb.sheetnames)
        if not ({SHEET_AEW, SHEET_AMW} & names):
            return 0.0
        score = 0.5 * len({SHEET_AEW, SHEET_AMW} & names)
        ws = wb[SHEET_AEW] if SHEET_AEW in names else wb[SHEET_AMW]
        header_tokens = {str(ws.cell(row=1, column=c).value or "").strip() for c in range(1, 23)}
        if "Include Surcharge" in header_tokens and "DEL Description" in header_tokens:
            score = min(score + 0.3, 1.0)
        return score

    def parse_raw(self, wb: Workbook) -> RawExtraction:
        scopes: dict[str, ScopeData] = {}
        for scope_name in (SHEET_AEW, SHEET_AMW):
            sheet_names = find_snapshot_sheets(wb, scope_name)
            if not sheet_names:
                continue
            occurrences = [_read_sheet(wb[name], scope_name).rows for name in sheet_names]
            scopes[scope_name] = ScopeData(scope=scope_name, rows=merge_dated_snapshots(occurrences))
        return RawExtraction(tables={"scopes": scopes})

    def _build_one_scope(self, data: ScopeData, config: MappingProfile) -> OpusRowSet:
        description = resolve_commodity_description(DEFAULT_COMMODITY_DESCRIPTION, config)
        code = resolve_commodity_code(DEFAULT_COMMODITY_DESCRIPTION, DEFAULT_COMMODITY_CODE, config)
        excluded_codes = frozenset(config.excluded_charge_codes)

        # CMDT NOTE grouping is data-driven (per-row validity dates +
        # Include Surcharge list) - see TAD-OEW-OMW's comment. The
        # multi-snapshot merge above already truncated the earlier
        # snapshot's validity_end, so its rows naturally form their own
        # distinct group here without any extra handling.
        group_order: list[tuple] = []
        group_rows: dict[tuple, list[RawRow]] = defaultdict(list)
        for row in data.rows:
            key = (row.validity_start, row.validity_end, tuple(row.included_codes))
            if key not in group_rows:
                group_order.append(key)
            group_rows[key].append(row)
        cmdt_seq_by_key = {key: i + 1 for i, key in enumerate(group_order)}

        rates: list[RatesRow] = []
        for row in data.rows:
            mapped = CARGO_TYPE_MAP.get(row.cargo_type)
            if mapped is None:
                continue
            prefix, cgo_type = mapped
            key = (row.validity_start, row.validity_end, tuple(row.included_codes))
            rates.append(
                RatesRow(
                    cmdt_seq=cmdt_seq_by_key[key],
                    commodity_group_code=code,
                    commodity_group_description=description,
                    origin_code=row.origin_code,
                    origin_description=row.origin_description,
                    origin_term=row.origin_term,
                    origin_transmode=row.origin_transmode,
                    o_via_code=row.pol,
                    d_via_code=row.pod,
                    destination_code=row.dest_code,
                    destination_description=row.dest_description,
                    destination_term=row.dest_term,
                    prefix=prefix,
                    cgo_type=cgo_type,
                    cur_20="USD" if row.rate_20 is not None else None,
                    rate_20=row.rate_20,
                    cur_40="USD" if row.rate_40 is not None else None,
                    rate_40=row.rate_40,
                    cur_40hc="USD" if row.rate_40hc is not None else None,
                    rate_40hc=row.rate_40hc,
                    cur_45="USD" if row.rate_45 is not None else None,
                    rate_45=row.rate_45,
                    route_note=_route_note_for(row.commodity_name, row.ts_port, row.service_lane),
                )
            )

        # D7 (OFT 45): opt-in only, D/DR rows only - see module docstring.
        if config.include_tad_d7:
            for r in rates:
                if r.prefix == "D" and r.cgo_type == "DR" and r.rate_40hc is not None:
                    r.cur_45 = "USD"
                    r.rate_45 = r.rate_40hc + config.tad_d7_addon

        # Opt-in only (config.generate_tad_dg_duplicate, default off) -
        # see TAD-OEW-OMW's identical comment. Runs after D7 so a
        # duplicate inherits its parent's rate_45 rather than lacking one.
        if config.generate_tad_dg_duplicate:
            rates.extend(
                row.model_copy(update={"cgo_type": "DG"}) for row in list(rates) if row.prefix == "D" and row.cgo_type == "DR"
            )

        # Route Seq.: one continuous counter per commodity group (same
        # scope rule confirmed for every TAD lane so far).
        for key in group_order:
            group = [r for r in rates if r.cmdt_seq == cmdt_seq_by_key[key]]
            for i, r in enumerate(group, start=1):
                r.route_seq = i

        cmdt_notes: list[CmdtNoteRow] = []
        note_text_by_seq: dict[int, str | None] = {}
        for key in group_order:
            validity_start, validity_end, codes = key
            seq = cmdt_seq_by_key[key]
            notes = self._build_cmdt_notes(validity_start, validity_end, list(codes), excluded_codes, config)
            for note in notes:
                note.header_seq = seq
            cmdt_notes.extend(notes)
            note_text_by_seq[seq] = notes[0].contents if notes else None

        for row in rates:
            row.commodity_note = note_text_by_seq.get(row.cmdt_seq)

        route_notes: list[RouteNoteRow] = []
        validity_by_seq = {cmdt_seq_by_key[key]: (key[0], key[1]) for key in group_order}
        for row in rates:
            if not row.route_note:
                continue
            validity_start, validity_end = validity_by_seq.get(row.cmdt_seq, (None, None))
            route_notes.append(
                RouteNoteRow(
                    header_seq=row.cmdt_seq,
                    route_seq=row.route_seq,
                    contents=row.route_note,
                    charge_seq=1,
                    code="APP",
                    application_effective=validity_start,
                    application_expires=validity_end,
                    application="S",
                )
            )

        return OpusRowSet(rates=rates, cmdt_notes=cmdt_notes, route_notes=route_notes)

    def _build_cmdt_notes(
        self,
        validity_start: date | None,
        validity_end: date | None,
        included_codes: list[str],
        excluded_codes: frozenset[str],
        config: MappingProfile,
    ) -> list[CmdtNoteRow]:
        codes = [c for c in included_codes if c not in excluded_codes]
        if not codes or validity_start is None or validity_end is None:
            return []
        unique_codes = sorted(dict.fromkeys(codes))
        names = {**CHARGE_CODE_NAMES, "HEA": _HEA_OVERRIDE}
        names_line = " and the ".join(f"{names.get(c, c)}({c})" for c in unique_codes)
        contents = "\n".join(
            [
                f"Rates are valid from {validity_start:%Y%m%d} to {validity_end:%Y%m%d}",
                f"Rates are inclusive of the {names_line}",
                "Rates are subject to all other surcharges including those, if any, "
                "specified in the contract and those published in the Governing Tariff(s) at the time of shipment.",
            ]
        )
        parent = CmdtNoteRow(
            contents=contents, charge_seq=1, code="APP",
            application_effective=validity_start, application_expires=validity_end, application="S",
        )
        child_effective = config.rfa_effective_date if config.rfa_effective_date is not None else validity_start
        child_expires = config.rfa_expiry_date if config.rfa_expiry_date is not None else validity_end
        children = [
            CmdtNoteRow(
                charge_seq=i + 2, code=c,
                application_effective=child_effective, application_expires=child_expires, application="I",
            )
            for i, c in enumerate(codes)
        ]
        return [parent, *children]

    def to_opus_rows(self, raw: RawExtraction, config: MappingProfile) -> OpusRowSet:
        # Single-scope entry point (BaseMRGParser.run()) - used when only
        # one of AEW/AMW is present in the workbook.
        scopes: dict[str, ScopeData] = raw.tables["scopes"]
        if not scopes:
            return OpusRowSet()
        return self._build_one_scope(next(iter(scopes.values())), config)

    def run_multi(self, wb: Workbook, config: MappingProfile | None = None) -> dict[str, OpusRowSet]:
        config = config or MappingProfile()
        raw = self.parse_raw(wb)
        scopes: dict[str, ScopeData] = raw.tables["scopes"]
        return {scope: self._build_one_scope(data, config) for scope, data in scopes.items()}


register(
    LayoutProfile(
        lane_id=TADAewAmwParser.lane_id,
        parser_cls=TADAewAmwParser,
        sheet_name_patterns=[r"^AEW$", r"^AMW$"],
        title_keywords=["EFFECTIVE DATE", "COMMODITY GROUP NAME", "INCLUDE SURCHARGE"],
        header_fingerprint=["DEL Description", "Include Surcharge"],
    )
)
